// Generated by gencpp from file waterplus_map_tools/AddNewWaypointResponse.msg
// DO NOT EDIT!


#ifndef WATERPLUS_MAP_TOOLS_MESSAGE_ADDNEWWAYPOINTRESPONSE_H
#define WATERPLUS_MAP_TOOLS_MESSAGE_ADDNEWWAYPOINTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace waterplus_map_tools
{
template <class ContainerAllocator>
struct AddNewWaypointResponse_
{
  typedef AddNewWaypointResponse_<ContainerAllocator> Type;

  AddNewWaypointResponse_()
    : result(false)  {
    }
  AddNewWaypointResponse_(const ContainerAllocator& _alloc)
    : result(false)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::waterplus_map_tools::AddNewWaypointResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::waterplus_map_tools::AddNewWaypointResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AddNewWaypointResponse_

typedef ::waterplus_map_tools::AddNewWaypointResponse_<std::allocator<void> > AddNewWaypointResponse;

typedef boost::shared_ptr< ::waterplus_map_tools::AddNewWaypointResponse > AddNewWaypointResponsePtr;
typedef boost::shared_ptr< ::waterplus_map_tools::AddNewWaypointResponse const> AddNewWaypointResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::waterplus_map_tools::AddNewWaypointResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::waterplus_map_tools::AddNewWaypointResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::waterplus_map_tools::AddNewWaypointResponse_<ContainerAllocator1> & lhs, const ::waterplus_map_tools::AddNewWaypointResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::waterplus_map_tools::AddNewWaypointResponse_<ContainerAllocator1> & lhs, const ::waterplus_map_tools::AddNewWaypointResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace waterplus_map_tools

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::waterplus_map_tools::AddNewWaypointResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::waterplus_map_tools::AddNewWaypointResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::waterplus_map_tools::AddNewWaypointResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::waterplus_map_tools::AddNewWaypointResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::waterplus_map_tools::AddNewWaypointResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::waterplus_map_tools::AddNewWaypointResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::waterplus_map_tools::AddNewWaypointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::waterplus_map_tools::AddNewWaypointResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb13ac1f1354ccecULL;
  static const uint64_t static_value2 = 0xb7941ee8fa2192e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::waterplus_map_tools::AddNewWaypointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "waterplus_map_tools/AddNewWaypointResponse";
  }

  static const char* value(const ::waterplus_map_tools::AddNewWaypointResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::waterplus_map_tools::AddNewWaypointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool result\n"
;
  }

  static const char* value(const ::waterplus_map_tools::AddNewWaypointResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::waterplus_map_tools::AddNewWaypointResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddNewWaypointResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::waterplus_map_tools::AddNewWaypointResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::waterplus_map_tools::AddNewWaypointResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WATERPLUS_MAP_TOOLS_MESSAGE_ADDNEWWAYPOINTRESPONSE_H
