// Generated by gencpp from file waterplus_map_tools/GetNumOfWaypointsRequest.msg
// DO NOT EDIT!


#ifndef WATERPLUS_MAP_TOOLS_MESSAGE_GETNUMOFWAYPOINTSREQUEST_H
#define WATERPLUS_MAP_TOOLS_MESSAGE_GETNUMOFWAYPOINTSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace waterplus_map_tools
{
template <class ContainerAllocator>
struct GetNumOfWaypointsRequest_
{
  typedef GetNumOfWaypointsRequest_<ContainerAllocator> Type;

  GetNumOfWaypointsRequest_()
    {
    }
  GetNumOfWaypointsRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::waterplus_map_tools::GetNumOfWaypointsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::waterplus_map_tools::GetNumOfWaypointsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetNumOfWaypointsRequest_

typedef ::waterplus_map_tools::GetNumOfWaypointsRequest_<std::allocator<void> > GetNumOfWaypointsRequest;

typedef boost::shared_ptr< ::waterplus_map_tools::GetNumOfWaypointsRequest > GetNumOfWaypointsRequestPtr;
typedef boost::shared_ptr< ::waterplus_map_tools::GetNumOfWaypointsRequest const> GetNumOfWaypointsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::waterplus_map_tools::GetNumOfWaypointsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::waterplus_map_tools::GetNumOfWaypointsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace waterplus_map_tools

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::waterplus_map_tools::GetNumOfWaypointsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::waterplus_map_tools::GetNumOfWaypointsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::waterplus_map_tools::GetNumOfWaypointsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::waterplus_map_tools::GetNumOfWaypointsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::waterplus_map_tools::GetNumOfWaypointsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::waterplus_map_tools::GetNumOfWaypointsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::waterplus_map_tools::GetNumOfWaypointsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::waterplus_map_tools::GetNumOfWaypointsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::waterplus_map_tools::GetNumOfWaypointsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "waterplus_map_tools/GetNumOfWaypointsRequest";
  }

  static const char* value(const ::waterplus_map_tools::GetNumOfWaypointsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::waterplus_map_tools::GetNumOfWaypointsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::waterplus_map_tools::GetNumOfWaypointsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::waterplus_map_tools::GetNumOfWaypointsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetNumOfWaypointsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::waterplus_map_tools::GetNumOfWaypointsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::waterplus_map_tools::GetNumOfWaypointsRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // WATERPLUS_MAP_TOOLS_MESSAGE_GETNUMOFWAYPOINTSREQUEST_H
